### ISSUE TITLE
Buildkite badge link is broken

### ISSUE THREAD

**Issue by jeznag** [cypress-io/cypress-example-kitchensink#152]
The buildkite badge link in the README returns 404. https://buildkite.com/cypress-io/cypress-example-kitchensink

**Comment by jennifer-shehane** [comment]
@bahmutov Did you have a login for this one?

**Comment by bahmutov** [comment]
Yes, we have stopped using Buildkite for our Mac builds - we have switched to CircleCI for Mac build. I have removed the badge, but have left the buildkite pipeline YAML file.
