### ISSUE TITLE
Setup Github Actions Build

### ISSUE THREAD

**Issue by kennethtruong** [cypress-io/cypress-example-kitchensink#210]
It would be great if there can be an example of Github Actions. 

When I try to run cypress in Github Actions I get this error about missing XVFB

```
$ run-p --race start:ci e2e
$ cypress run
$ http-server app -c-1 --silent
It looks like this is your first time using Cypress: 3.1.5

�[?25l[20:38:23]  Verifying Cypress can run /github/home/.cache/Cypress/3.1.5/Cypress [started]
[20:38:23]  Verifying Cypress can run /github/home/.cache/Cypress/3.1.5/Cypress [failed]
[20:38:23] → Your system is missing the dependency: XVFB

Install XVFB and run Cypress again.
```

**Comment by pcraig3** [comment]
Hey! For anyone else who comes across this problem, you can switch your action to [npm-cy](https://github.com/bartlett705/npm-cy) and then your cypress command line test will run on github actions.

[Here is an example implementation](https://github.com/cds-snc/cra-alpha/pull/30/commits/979aff9b7f775676fb5c8034e2473539bc0c536e).
