### ISSUE TITLE
Add Licence file

### ISSUE THREAD

**Issue by yochannah** [cypress-io/cypress-example-kitchensink#238]
Hi! Thank you so much for making such an awesome repo with so many good examples. 

I was thinking to copy/paste some code from here to my repo, which I'm guessing is one of the purposes of this repo, but when I went to check if that was okay, I couldn't spot a LICENSE file. Apologies if I missed it! Adding a licence would make it a lot clearer if it's okay to re-use the code in this repo. 

I'd be happy to make a PR to do this myself if I'm right in thinking this should be MIT, as noted here: https://github.com/cypress-io/cypress-example-kitchensink/blob/cd39200627a667dc7faa7852a88ce77c063a1521/package.json#L47

**Comment by jennifer-shehane** [comment]
😯 Yes, please open a PR to add the LICENSE.md file. Should match https://github.com/cypress-io/cypress/blob/develop/LICENSE.md
