### ISSUE TITLE
cy.exec() example fails in windows (cannot use cat in windows)

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-example-kitchensink#27]
The example spec needs to be updated and re-deployed.

<img width="838" alt="screen shot 2017-11-30 at 10 32 19 am" src="https://user-images.githubusercontent.com/1271364/33438896-0bd6e992-d5ba-11e7-8465-e37d7f4e5c16.png">

**Comment by bahmutov** [comment]
We should first implement a Cypress function that would return current platform, so we can skip this test on Windows, or use different command.

**Comment by brian-mann** [comment]
https://github.com/cypress-io/cypress/issues/824
