### ISSUE TITLE
Consider a IBM Development Pipeline Example

### ISSUE THREAD

**Issue by iamgollum** [cypress-io/cypress-example-kitchensink#281]
It would be useful if Cypress had an example for the IBM Developer Pipeline. 

I will work on this on behalf of my employer since I use Cypress at work all the time.

**Comment by bahmutov** [comment]
Sure @iamgollum - can you point me where I can sign up for it? I can set it up, or at least look at it

**Comment by iamgollum** [comment]
Hi @bahmutov I am working with the Cloud Pipeline team right now so let me be in touch. 
The docs are outdated and there is a slew of changes I need to try out.

I have a working custom Cypress docker stage through the GUI already.

**Comment by bahmutov** [comment]
Super @iamgollum - you can also use https://github.com/cypress-io/cypress-docker-images for Docker images, usually makes the setup pretty simple

**Comment by iamgollum** [comment]
@bahmutov that is exactly what I used. Fantastic!

**Comment by iamgollum** [comment]
@bahmutov I am close. I exposed a bug on a custom docker image ... the key attribute pair in the YAML is not being read properly so the IBM Cloud Pipeline team is working on a fix. Ill keep you updated.

**Comment by bahmutov** [comment]
Nice, looking forward to it
