### ISSUE TITLE
Issues running CI in Jenkins

### ISSUE THREAD

**Issue by alastair-todd** [cypress-io/cypress-example-kitchensink#293]
Having failed to get cypress running in AWS Linux 2, I'm trying the Docker example on the same instance. Stock Jenkins file as per this repo, other than to update the cypress image to the included one.

However I've some messages I could do with help deciphering. Seems to stall on `npm ci`

> [Pipeline] withDockerContainer
Jenkins seems to be running inside container e027379c59ac1c6c85fb3a167630b83dc3d535277209791dcccefb935de08012
$ docker run -t -d -u 0:0 -w /var/jenkins_home/workspace/elc-cypress-ci-pipeline --volumes-from e027379c59ac1c6c85fb3a167630b83dc3d535277209791dcccefb935de08012 -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** cypress/included:3.4.1 cat
$ docker top 73dff70c31edc1e50e867a029d6aa8ac308e92082947136beb876c8a26cda2c4 -eo pid,comm
ERROR: The container started but didn't run the expected command. Please double check your ENTRYPOINT does execute the command passed as docker run argument, as required by official docker images (see https://github.com/docker-library/official-images#consistency for entrypoint consistency requirements).
Alternatively you can force image entrypoint to be disabled by adding option `--entrypoint=''`.
[Pipeline] {
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] echo
Running build 4 on http://34.242.176.131:8080/
[Pipeline] sh

> + npm ci
> wrapper script does not seem to be touching the log file in /var/jenkins_home/workspace/elc-cypress-ci-pipeline@tmp/durable-778b0f20
> (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)

**Comment by bahmutov** [comment]
Noting comes to mind from looking at these messages, have you been able to run the same docker image locally?

**Comment by alastair-todd** [comment]
I've changed to `cypress/base:12.6.0` and things are much better.
However, this is an angular app using webpack - I'm aware of the start and wait issue. 

Can you use the start and test package with the parallel example in the Jenkins file?

**Comment by bahmutov** [comment]
Sure, see our Jenkins example for starting the server in the background
- https://github.com/cypress-io/cypress-example-kitchensink/blob/master/Jenkinsfile
You can also use this utility https://github.com/bahmutov/start-server-and-test to start the server, wait for it to build and respond and then run tests. It even shuts down the server after the tests are done.

**Comment by alastair-todd** [comment]
@bahmutov the problem is: start-test expects to be testing after waiting, but anyway, there's no waiting at all in jenkins

> [?25l[14:03:03]  Verifying Cypress can run /root/.cache/Cypress/3.4.1/Cypress [started]
[14:03:06]  Verifying Cypress can run /root/.cache/Cypress/3.4.1/Cypress [completed]
[?25h[?25h
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (start local server)
[Pipeline] sh
+ nohup npm run start:wait
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (cypress parallel tests)
[Pipeline] withEnv
[Pipeline] {
[Pipeline] parallel
[Pipeline] { (Branch: tester A)
[Pipeline] { (Branch: tester B)
[Pipeline] stage
[Pipeline] { (tester A)
[Pipeline] stage
[Pipeline] { (tester B)
[Pipeline] echo
Running build 8
[Pipeline] sh
[Pipeline] echo
Running build 8
[Pipeline] sh
+ npm run cy:record:parallel
+ npm run cy:record:parallel

> seemis-workspace@0.1.1 cy:record:parallel /var/jenkins_home/workspace/elc-cypress-ci-pipeline
> cypress run --record --key 67fe2ba0-e6de-4681-8b70-e5d54dea1159 --parallel


> seemis-workspace@0.1.1 cy:record:parallel /var/jenkins_home/workspace/elc-cypress-ci-pipeline
> cypress run --record --key 67fe2ba0-e6de-4681-8b70-e5d54dea1159 --parallel

Cypress could not verify that this server is running:

  > http://localhost:4200

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
Cypress could not verify that this server is running:

  > http://localhost:4200

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

We will try connecting to it 1 more time...

`"start:wait": "start-server-and-test start http-get://localhost:4200 echo"`

**Comment by bahmutov** [comment]
not sure what you mean - "no waiting on Jenkins". Don't you start the server to run at `http://localhost:4200`? Since this is probably webpack dev server, with its own quirks, you probably need to use `http-get://localhost:4200` url form, see https://github.com/bahmutov/start-server-and-test#note-for-webpack-dev-server-users

**Comment by alastair-todd** [comment]
Jenkins does not wait, it jumps straight to the "test" stage.

Anyway, start and test kills the process as it expects to test after waiting so I don't see how it can work with parallel execution in this set up.

**Comment by bahmutov** [comment]
Well, see my link above where I start a single background server and run servers in parallel. You can use an utility https://github.com/jeffbski/wait-on to make sure the server is up and running before starting tests

**Comment by vandammeb** [comment]
@alastair-todd @bahmutov I'm experiencing the same problem you mentioned here (https://github.com/cypress-io/cypress-example-kitchensink/issues/293#issue-495786657), how was that related to the image you were using? (I'm on cypress/included:6.4.0)
