### ISSUE TITLE
Add AWS Amplify Example

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-example-kitchensink#296]
To assist with the AWS Amplify Console integration with Cypress:
- [x] Add `amplify.yml` to show an example Amplify configuration working Cypress
- [x] Update README to include Amplify under the [CI Status](https://github.com/cypress-io/cypress-example-kitchensink#ci-status) section.

**Comment by kevinold** [comment]
PR https://github.com/cypress-io/cypress-example-kitchensink/pull/300
