### ISSUE TITLE
Cypress as UAT tool for Front end

### ISSUE THREAD

**Issue by apjden585** [cypress-io/cypress-example-kitchensink#299]
Hi All Cypress Geniuses,

So, I am already a fan of cypress and have comfortably automated my front end, integrated to Azure Devops, generated reports etc. All is going great.

What I would like to do now is to integrate Cypress to my front end. I want to give my end customers a dashboard on the same website where they can run the test (UAT) on there own. 
Its a far fetched idea and not sure what I am talkin even makes any sense but would like to hear from you guys.

**Comment by iamgollum** [comment]
@apjden585 want to work on a new side project to create something like Swagger for UAT focused on Cypress. Beyond that, it would probably involve the parsing the results from the CLI and exposing it behind an API or this is a secret future feature for Cypress.io itself...

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress the example kitchensink app. If you want to report a bug or request a feature on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
