### ISSUE TITLE
cypress.run is not working on heroku

### ISSUE THREAD

**Issue by anil826** [cypress-io/cypress-example-kitchensink#306]
I just want to understand what could be the resion why this `cypress.run` is not working on heroku only working on local setup.

```js
var step = require('step');
var request = require('request');
const cypress = require('cypress')

module.exports = function(app){

  return {
    //Helper method for pdf service status
    test_status: function( callback ) {
      console.log("Check log....!!! ")
      //Cypress run
      cypress.run({
        spec: './cypress/integration/test_spec.js'
      })
      .then((results) => {
        //Return the response data
        callback(results)
      })
      .catch((err) => {
        //Retrun error
        callback(err)
      })
    }
  };
};
```

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress our example kitchensink app. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
