### ISSUE TITLE
Remove mention of Heroku CI support

### ISSUE THREAD

**Issue by Pro777** [cypress-io/cypress-example-kitchensink#324]
Heroku's cedar-14 stack is now [EOL](https://devcenter.heroku.com/changelog-items/1603).

The heroku buildpack required for Cypress to function is not compatible with newer stacks, so can references to compatibility with Heroku CI be removed?

**Comment by flotwig** [comment]
Hey @Pro777, yeah, I tried updating the stack to `heroku-18` in #325 and it fails with this error:

```
-----> Xvfb Google Chrome app detected
 !     The Google Chrome Xvfb buildpack is only supported on Cedar-14.
 !     For newer stacks you must instead use Google Chrome Buildpack,
 !     which runs Chrome in headless mode without Xvfb.
 !     For more details use:
 !     https://devcenter.heroku.com/articles/heroku-ci#known-issues
```

I don't think that Heroku CI should be removed, as `cedar-14` still "works", but it is very old and definitely needs to be updated. I see @bahmutov has run in to this before: #214 

I don't see why xvfb wouldn't work in `heroku-18`, so I think if the buildpack was updated to work with `heroku-18`, this could be fixed.

**Comment by bahmutov** [comment]
Well, `cedar-14` is mostly failing with `SIGILL` like https://github.com/cypress-io/cypress-example-kitchensink/pull/385 so it would be nice to fully support headless Cypress (right now we can do headless browser mode, but not Cypress itself, right @flotwig)

**Comment by flotwig** [comment]
correct @bahmutov, Electron still needs a display manager to run, so we still need `xvfb-run` just for Electron... once we remove Electron from cypress's core, it will not need xvfb for headless mode

**Comment by bahmutov** [comment]
I will disable our CI Heroku project, because it just keeps failing, breaking our status checks, but I will keep this issue open, because once we remove Electron we should enable it back

**Comment by erwanriou** [comment]
Ok interesting, I was fighting with heroku and not understunding why i had this SIGILL Error since i was folowing all the steps. I had the project detected in cypress dashboard (but no info about it). So this is due to this deprecated build of chrome. 

So @bahmutov do we have a roadmap of when electron will be removed?

**Comment by jennifer-shehane** [comment]
You can follow the issue about removing Electron from Cypress core here: https://github.com/cypress-io/cypress/issues/3899

**Comment by Pro777** [comment]
Cedar-14 stack EOL has been [delayed](https://devcenter.heroku.com/changelog-items/1603) until November 2, 2020 due to COVID-19.

**Comment by savannahp** [comment]
I am currently writing a bunch of cypress test right now and we use Heroku CLI, will this not work if we want to make it part of the pipeline?

**Comment by bahmutov** [comment]
Unfortunately because of Heroku limitations I don't think Cypress can run on it unless we make it fully headless so it does not need xvfb. I would suggest trying another CI that could even be triggered after Heroku finishes the deploy

**Comment by xyNNN** [comment]
I would like to use cypress on the heroku ci. Is there no other way to make it work?

**Comment by sec0ndhand** [comment]
I'm sorry this issue got re-opened, but it looks like there is some hope with [this issue/pr](https://github.com/cypress-io/cypress/issues/16505)
