### ISSUE TITLE
Need IDs for headings so that we can link anchor tags

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-kitchensink#356]
For example, I want to show "cy.check()" examples by sending an URL. But there is no URL to send - only the top-level page https://example.cypress.io/commands/actions.

<img width="1440" alt="Screen Shot 2020-02-04 at 9 15 16 PM" src="https://user-images.githubusercontent.com/2212006/73805123-cb03a600-4793-11ea-996b-2b56faf7b606.png">

**Comment by dburugupalli** [comment]
@jennifer-shehane, I would like to take up this issue and 

I have one question, what would be the name of the id ? to link with

**Comment by jennifer-shehane** [comment]
@dburugupalli The name of the command that is in the heading, so for `.check()` the heading should be `id="check"` so that the hashtag is `#check`

**Comment by dburugupalli** [comment]
@jennifer-shehane Thank you .

**Comment by dburugupalli** [comment]
@jennifer-shehane I have raised a PR for this issue
Below mentioned is the link for the Pull Request Raised. Please review my PR, also provide me with insights about some of the issues that i can take up. 

https://github.com/cypress-io/cypress-example-kitchensink/pull/372

**Comment by dburugupalli** [comment]
#372

**Comment by jennifer-shehane** [comment]
Hey @dburugupalli I see the PR is closed.

**Comment by NoelArzola** [comment]
If this still needs done I'd love to take a swing at it

**Comment by jennifer-shehane** [comment]
@NoelArzola Yes, feel free to open a PR.

**Comment by NoelArzola** [comment]
@jennifer-shehane Thank you so much, submitted

**Comment by NoelArzola** [comment]
@jennifer-shehane I have added IDs to the other pages for review PR #390, thanks!
