### ISSUE TITLE
No commit info for one of our CI runs in kitchensink repo

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-example-kitchensink#371]
I was reviewing the runs from a test PR of mine and there is this run in the Dashboard that has no commit info. It's hard to pick out which one this is since there's a million CI runs, but I'd like it tracked down so we can fix this if possible. 

https://dashboard.cypress.io/projects/4b7344/runs/13207/specs

**Comment by MikeMcC399** [comment]
This is a stale issue.
