### ISSUE TITLE
Mochawesome 5.0.0 update breaks Amplify test command

### ISSUE THREAD

**Issue by patleeman** [cypress-io/cypress-example-kitchensink#373]
Please see https://github.com/aws-amplify/amplify-console/issues/466

This affects the command [here](https://github.com/cypress-io/cypress-example-kitchensink/blob/0ead7854f8e893854becb29e2deb982dab37576d/amplify.yml#L29).

**Comment by kevinold** [comment]
@patleeman Thanks for the report!  Fixing this here and in our docs.
