### ISSUE TITLE
Typo in cookies.html 

### ISSUE THREAD

**Issue by NoelArzola** [cypress-io/cypress-example-kitchensink#389]
I noticed on the cookies page line 146 says cy.clearCookies() vs cy.clearCookie()
I think this is a typo because cy.clearCookies() is it's own section below and the rest of this section is singular
I didn't want to change this without a go-ahead first

**Comment by jennifer-shehane** [comment]
Yes, this is a typo - feel free to open a PR.

**Comment by NoelArzola** [comment]
Thank you PR submitted @jennifer-shehane

**Comment by jennifer-shehane** [comment]
Closed in https://github.com/cypress-io/cypress-example-kitchensink/pull/394
