### ISSUE TITLE
Prioritize Cypress dependency update

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-kitchensink#410]
Right now we are trying to keep all dependencies up-to-date using Renovate Bot, which is rate-limited. But `cypress` itself, which is the most important dependency here gets lost in the long queue. For example, we are going to release `cypress@4.6.0` today, yet here `cypress` is still on 4.4.1!

## Proposal

- limit dependency updates to most necessary ones following https://glebbahmutov.com/blog/whitelist-renovate/
- add a badge to the README with cypress version to quickly see if the update has not happened in a while and something is wrong, using https://github.com/bahmutov/dependency-version-badge

**Comment by MikeMcC399** [comment]
Renovate seems to be working successfully for updating Cypress.

- See for instance https://github.com/cypress-io/cypress-example-kitchensink/pull/893
