### ISSUE TITLE
Release is blocked - using semantic release does not release new version

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-example-kitchensink#419]
Automatic releases via semantic-release have been blocked ever since 1.10.0.

You can see there have been several commits since March 18, 2020 that should have triggered a release but failed including this one which used the `feature` comment: https://github.com/cypress-io/cypress-example-kitchensink/commit/1bfff99ac7db3e5447b77746c5176193906451b8

This is now blocking PRs to our Test Runner including this one which will require a kitchensink release: https://github.com/cypress-io/cypress/pull/7445

(On top of this - our updating of kitchensink is blocked in the TR repo itself because the update fails in Appveyor: https://github.com/cypress-io/cypress/pull/7282)

**Comment by bahmutov** [comment]
`feature: try to release again` is not an official semantic prefix :) `feat:` is

**Comment by bahmutov** [comment]
Let's see now https://github.com/cypress-io/cypress-example-kitchensink/commit/aadcb60cc0571f041d050b021b5d81d4b55b1af1 in https://circleci.com/workflow-run/400f2fcd-3776-440f-ba06-44604b1da1ae

**Comment by bahmutov** [comment]
published

**Comment by jennifer-shehane** [comment]
omg, really? 🙄 They should alias that keyword.
