### ISSUE TITLE
FEATURE Request: Do not start new browser for each unit test in run mode

### ISSUE THREAD

**Issue by tomitrescak** [cypress-io/cypress-example-kitchensink#422]
Hi, I know this is a feature of Cypress since v3 but it would be great if the unit tests could all rn in the same browser in run mode. Otherwise it takes a LONG time to execute them all (e.g. we have 367 unit test files for all our components and needs).

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to the Cypress kitchensink examples at https://example.cypress.io. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
