### ISSUE TITLE
Run All Specs does not work with unit tests

### ISSUE THREAD

**Issue by tomitrescak** [cypress-io/cypress-example-kitchensink#423]
Hi I'm running the latest version of Cypress and trying to execute all my unit tests in the "open" mode. When I press the "Run All Specs" button following error comes up:

![image](https://user-images.githubusercontent.com/2682705/83632096-ff705d00-a5e1-11ea-92fb-be60fdf8097b.png)

Individually all works as expected.

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to the Cypress kitchensink examples at https://example.cypress.io. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
