### ISSUE TITLE
exception occured when starting project

### ISSUE THREAD

**Issue by maxime-aubry** [cypress-io/cypress-example-kitchensink#428]
Hello.

I have an error when i type an npm start command on your cypress-example-kitchensink-master project.

What can I do ?
thanks

> ERROR: Unknown --listen endpoint scheme (protocol): null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress-example-kitchensink@0.0.0-development start: `serve --listen ${PORT:-8080}`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress-example-kitchensink@0.0.0-development start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:...

**Comment by maxime-aubry** [comment]
thanks.
here is the log file content :

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\maxim\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.14.3
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cypress-example-kitchensink@0.0.0-development~prestart: cypress-example-kitchensink@0.0.0-development
6 info lifecycle cypress-example-kitchensink@0.0.0-development~start: cypress-example-kitchensink@0.0.0-development
7 verbose lifecycle cypress-example-kitchensink@0.0.0-development~start: unsafe-perm in lifecycle true
8 verbose lifecycle cypress-example-kitchensink@0.0.0-development~start: PATH: C:\Users\maxim\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\maxim\Downloads\cypress-example-kitchensink-master\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\TortoiseGit\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;D:\DevTools\Android\Sdk\platform-tools;C:\Program Files\nodejs\;C:\Program Files\Dart\dart-sdk\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\flutter\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Dart\dart-sdk\bin;C:\Users\maxim\AppData\Roaming\npm;C:\Users\maxim\.dotnet\tools;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle cypress-example-kitchensink@0.0.0-development~start: CWD: C:\Users\maxim\Downloads\cypress-example-kitchensink-master
10 silly lifecycle cypress-example-kitchensink@0.0.0-development~start: Args: [ '/d /s /c', 'serve --listen ${PORT:-8080}' ]
11 silly lifecycle cypress-example-kitchensink@0.0.0-development~start: Returned: code: 1  signal: null
12 info lifecycle cypress-example-kitchensink@0.0.0-development~start: Failed to exec start script
13 verbose stack Error: cypress-example-kitchensink@0.0.0-development start: `serve --listen ${PORT:-8080}`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\maxim\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\maxim\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid cypress-example-kitchensink@0.0.0-development
15 verbose cwd C:\Users\maxim\Downloads\cypress-example-kitchensink-master
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\maxim\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.3
19 verbose npm  v6.14.3
20 error code ELIFECYCLE
21 error errno 1
22 error cypress-example-kitchensink@0.0.0-development start: `serve --listen ${PORT:-8080}`
22 error Exit status 1
23 error Failed at the cypress-example-kitchensink@0.0.0-development start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by maxime-aubry** [comment]
I have the same bug with another project.

**Comment by jennifer-shehane** [comment]
@maxime-aubry Are you sure you ran `npm i`? This is failing on the `start` script and has nothing to do with Cypress itself.

**Comment by thisuraseniya** [comment]
@maxime-aubry since you are running Windows, the command you should use is `npm run start:ci:windows`

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by pablogiroud** [comment]
> @maxime-aubry since you are running Windows, the command you should use is `npm run start:ci:windows`

@jennifer-shehane maybe we can mark @maxime-aubry comment as solution. I'm here for the same issue, and it's works.

Thanks for all (always) <3

**Comment by rudupa68** [comment]
npm run start:ci:windows - this didn't help

**Comment by AramLR** [comment]
Change the start command on package.json to 'serve'
![Screenshot_1](https://user-images.githubusercontent.com/72953797/160964124-d05ec7df-5c13-4981-96c5-d400feddb288.png)
That worked for me

**Comment by lukszits** [comment]
I suggest changing the port for those still having a problem after using `npm run start:ci:windows`
![image](https://user-images.githubusercontent.com/45823480/161045989-3b72f635-4cfb-4a32-9119-1f8d9b5b16a9.png)

**Comment by flotwig** [comment]
This seems to happen only on Windows. Reopening.
