### ISSUE TITLE
Typo Error - find() command has description and link of filter() command in the traversal section

### ISSUE THREAD

**Issue by sundarcodes** [cypress-io/cypress-example-kitchensink#43]
![screenshot-2018-1-31 cypress io kitchen sink](https://user-images.githubusercontent.com/10928793/35634375-946d4c4a-06d1-11e8-881d-de225958252a.png)

**Comment by sundarcodes** [comment]
I wanted to submit a PR for this but couldn't find the detailed contributing guidelines. BTW, I have started to become a big fan of cypress 👍  Great job guys !!

**Comment by jennifer-shehane** [comment]
We have not written a detailed contributing guideline 😞  Thanks for opening the issue.

**Comment by MikeMcC399** [comment]
- Resolved in https://github.com/cypress-io/cypress-example-kitchensink/pull/44 Jan 2018
