### ISSUE TITLE
how to debug in  Testrunner

### ISSUE THREAD

**Issue by ycwdaaaa** [cypress-io/cypress-example-kitchensink#432]
if I want to debug my test cases, what should I do?  What I want is to pause the  case in one step and see what happen in browser.  I tried to the debug command but the test runner always run the whole case.

**Comment by jennifer-shehane** [comment]
@ycwdaaaa Please see our guide on debugging in cypress: https://on.cypress.io/debugging

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
