### ISSUE TITLE
Amplify get stuck while starting tests

### ISSUE THREAD

**Issue by keponk** [cypress-io/cypress-example-kitchensink#446]
Similar to previous issues. The boilerplate at https://github.com/cypress-io/cypress-example-kitchensink/blob/master/amplify.yml was not working for me.

Looking online I found this comment on amplify's issue tracker https://github.com/aws-amplify/amplify-console/issues/583
This worked for me on a simple react app. Since they are taking a while to update would be good to link it here.

**Comment by jennifer-shehane** [comment]
We're open to a PR to update this!

**Comment by MikeMcC399** [comment]
- PR #447 was submitted without merge and this issue is now stale.
