### ISSUE TITLE
Disconnect Codeship CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-kitchensink#464]
Seems to not be working

<img width="1440" alt="Screen Shot 2020-12-02 at 12 56 27 PM" src="https://user-images.githubusercontent.com/2212006/100915317-30065600-34a2-11eb-9de8-53ae6c6ee6d5.png">

**Comment by MikeMcC399** [comment]
This issue should be closed.

The [CodeShip Pro workflow](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/basic/codeship-pro) is no longer live.
