### ISSUE TITLE
Disconnect Travis CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-kitchensink#465]
Seems to queue jobs forever, not sure if they are working at all

**Comment by bahmutov** [comment]
The CI is not running for hours

<img width="1051" alt="Screen Shot 2020-12-02 at 3 30 32 PM" src="https://user-images.githubusercontent.com/2212006/100927791-5bde0780-34b3-11eb-8e61-145d569eb505.png">

**Comment by bahmutov** [comment]
ughh, it seems I cannot disconnect Travis CI

<img width="1072" alt="Screen Shot 2020-12-02 at 3 39 39 PM" src="https://user-images.githubusercontent.com/2212006/100928794-ad3ac680-34b4-11eb-99fd-41c50b381802.png">

**Comment by MikeMcC399** [comment]
This issue should be closed. 

The [Travis workflow](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.travis.yml) is no longer live.
