### ISSUE TITLE
Test example on https://example.cypress.io/utilities does not work

### ISSUE THREAD

**Issue by vitaliy4us** [cypress-io/cypress-example-kitchensink#469]
Test example on https://example.cypress.io/utilities does not work

Steps to reproduce:

1. Create a test following the instructions provided in Cypress.Blob section of the page https://example.cypress.io/utilities
2. Run the test in Cypress Runner
Expected result: The test passes
Actual result: the test fails, an error "Timed out retrying after 4000ms: Expected to find element: .utility-blob img, but never found it" arises. [See attached image](https://ibb.co/G0wNpHx).

**Comment by jennifer-shehane** [comment]
@vitaliy4us It looks like the image did not load for some reason when you ran the test. Is this reproducible every time for you? I wasn't able to reproduce the issue.

**Comment by vitaliy4us** [comment]
@jennifer-shehane Yes, this is 100% reproducible on my side and the reason is this command that returns an empty object:
`let img = Cypress.$('', { src: dataUrl });`
while dataUrl is ok and is downloaded successfully.

**Comment by bahmutov** [comment]
Notice that the test

```js
cy.get('.utility-blob').then(($div) => {
  // https://github.com/nolanlawson/blob-util#imgSrcToDataURL
  // get the dataUrl string for the javascript-logo
  return Cypress.Blob.imgSrcToDataURL('/assets/img/javascript-logo.png', undefined, 'anonymous')
  .then((dataUrl) => {
    // create an <img> element and set its src to the dataUrl
    let img = Cypress.$('<img />', { src: dataUrl })

    // need to explicitly return cy here since we are initially returning
    // the Cypress.Blob.imgSrcToDataURL promise to our test
    // append the image
    $div.append(img)

    cy.get('.utility-blob img').click()
      .should('have.attr', 'src', dataUrl)
  })
})
```

requires loading a local image file from `/assets/img/javascript-logo.png`. This is present in this repository https://github.com/cypress-io/cypress-example-kitchensink/tree/master/app/assets/img but not if you just create your own spec.

Replace `/assets/...png` with URL to a valid image resource and it should work

**Comment by vitaliy4us** [comment]
I use a valid resource https://example.cypress.io/assets/img/javascript-logo.png and command:
` const img = Cypress.$('', { src: dataUrl });`
returned this image
But the problem is this command
`const img = Cypress.$('', { src: dataUrl });`
which returned empty value to img constant

Here is the test:

`it('To work with blobs, convert strings, and other utility functions, use the Cypress.Blob library', () => {
    cy.get('.utility-blob').then(($div) =>
      Cypress.Blob.imgSrcToDataURL(
        'https://example.cypress.io/assets/img/javascript-logo.png',
        undefined,
        'anonymous'
      ).then((dataUrl) => {
        const img = Cypress.$('', { src: dataUrl });
        $div.append(img);
        cy.get('.utility-blob img').click().should('have.attr', 'src', dataUrl);
      })
    );`
