### ISSUE TITLE
Selecting Options Using the Vue Select Element

### ISSUE THREAD

**Issue by hkarambizi** [cypress-io/cypress-example-kitchensink#478]
Vue Select Element is not a select element and needs a workaround to select options. 

There have been some workarounds posted in [StackOverflow](https://stackoverflow.com/questions/60398735/vuetify-select-component-and-cypress). Would be nice to include an example implementation.

**Comment by MikeMcC399** [comment]
This is a stale suggestion and is not specific to `cypress-example-kitchensink`.
