### ISSUE TITLE
.scrollTo times out in kitchensink tests

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-example-kitchensink#492]
This `.scrollTo()` times out very frequently in the kitchensink tests. Sometimes the bug shows up as a `.screenshot()` timeout after the scrollTo fails.

Seems to fail mostly in CircleCI Mac, Electron and also in Windows Appveyor. 

CircleCI failure: https://app.circleci.com/pipelines/github/cypress-io/cypress-example-kitchensink/1063/workflows/081e2595-85f7-4cc9-a5f7-fa3f23006b8e/jobs/6905
Appveyor failure:

**Comment by MikeMcC399** [comment]
This issue is no longer being observed.
