### ISSUE TITLE
buildekite example for parallel test execution with dashboard isn't too clear

### ISSUE THREAD

**Issue by country-bumpkin-software** [cypress-io/cypress-example-kitchensink#527]
Hi there,

Im finding it difficult to find examples of how I can set up parallel tests in Buildkite that integrates with cypress dashboard.

I got the dashboard integrated and working but I cant find a good simple example how to get basic parallel tests running on Buildkite.

Any help available on this ? I mean in the Buildkite.yml I couldn't figure out how to enable this 

I did try to add the "parallelism: 3" but this just created 3 agents and ran all of my tests in each agent so I didnt get any parallel tests running just multiple agents

**Comment by country-bumpkin-software** [comment]
ok I figured out if I just add:

parallelism: 3

to my e2e block on the Buildkite.yml file then it works.

Also I have to add:
--ci-build-id $BUILDKITE_BUILD_ID

to my npm script (before I was using BUILDKITE_JOB_ID which are all unique so maybe thats why it didnt work right first time round)

Hopefully this is of some help to people using Buildkite.

**Comment by smendoza787** [comment]
Worked for me!

These docs were were also helpful.
https://docs.cypress.io/guides/cloud/smart-orchestration/parallelization#CI-Build-ID-environment-variables-by-provider
