### ISSUE TITLE
Bad link to https://placehold.it/100x100 causes cypress tests to hang or run very slowly

### ISSUE THREAD

**Issue by carylewis** [cypress-io/cypress-example-kitchensink#537]
I wanted to run the kitchen sink tests on the example.cypress.io website rather than run the site locally. After updating the tests to reference the example.cypress.io domain rather than localhost:8080, I discovered that each cypress test in the 2-advanced-examples/actions.spec.js file were either failing or taking a very long time to run.

The root cause of this delay is a reference to https://placehold.it/100x100 in the app/commands/actions.html file, which redirects to https://www.placeholder.com/100x100, which then redirects to https://placeholder.com/100x100. 

That URL is broken and returns a 500 error, but it can take up to 60 seconds for that to happen, which causes the cypress tests to run either very slowly (as the beforeEach() loads the https://example.cypress.io/commands/actions page before each cy.visit).

I thought I would post this in case anyone else encountered this.

Note: This problem exists even if you're running the site locally.

**Workaround**

To work around this, you can replace the references to https://placehold.it/100x100 in the app/commands/actions.html file with https://via.placeholder.com/100x100

**Comment by BlueWinds** [comment]
Thanks for the report! We've fixed this in the latest release, 1.15.3, by removing the placeholder images entirely and just using styled divs (see https://github.com/cypress-io/cypress-example-kitchensink/pull/540).

**Comment by carylewis** [comment]
When will that release be available?

**Comment by BlueWinds** [comment]
It's available on github (in the master branch) and on NPM right now. Still working through some issues with the deployment; hopefully it'll be on example.cypress.io by end of day, as soon as I work out the remaining hurdles.
