### ISSUE TITLE
Issues with cypress 9.0 runner , multiple describe is not working

### ISSUE THREAD

**Issue by Gayathri-Kesavakannan** [cypress-io/cypress-example-kitchensink#558]
Issue 1: Runner/ test is not refreshed for second describe. Second describe is not loading application it just retains previous test 

Issue2: when I click on close in test runner execution window it's not closing runner. I need to click on "stop " in other cy window 

Issue1 
I have test with multiple describe where I will launch my application . 

Describe(first)
Before{ 
visitandlogin(user1)
}
{
  It(1){}
  It(2){}
}
Describe(second)

Before{ 
visitandlogin(user2)
}
{
  It(1){}
  It(2){}
}

Headless it's working fine , but when I test headed I. cypress9.0 describe1 is tested but describe 2 is not loading page it's still in page of describe 1

**Comment by MikeMcC399** [comment]
This issue does not seem to be related to `cypress-example-kitchensink`. It is stale and related to the legacy Cypress 9.x version.
