### ISSUE TITLE
Attempting to run on Mac M1 fails - The chromium binary is not available for arm64.

### ISSUE THREAD

**Issue by carylewis** [cypress-io/cypress-example-kitchensink#562]
After cloning the repo and running:

`npm install --save-dev cypress`

I encounter this error:

```
npm ERR! code 1
npm ERR! path /Users/xxxxxxx/workspace/cypress-example-kitchensink/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  sudo apt install chromium
npm ERR! 
npm ERR! 
npm ERR!  sudo apt install chromium-browser
npm ERR! 
npm ERR! /Users/xxxxxxxx/workspace/cypress-example-kitchensink/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115

```
I manually install chromium, which worked but still can't get cypress to install in the project?

Other cypress examples such as https://github.com/cypress-io/cypress-example-recipes work fine.

**Note: cypress-example-kitchensink fails when node 16.16.0 is used, but does work if node 14.20 is used.**

**Comment by cattrn** [comment]
Not a fix, but if you're not using Netlify, you can also remove `netlify-plugin-cypress` (plus relevant Netlify and `puppeteer` related config if you wish) to make the install successful.

**Comment by MikeMcC399** [comment]
@carylewis 

This is an old issue, and I'm wondering what version of Cypress was being used at the time. Are you still having this problem?

Cypress [10.2.0](https://docs.cypress.io/guides/references/changelog#10-2-0) introduced native M1 support.

**Comment by carylewis** [comment]
I can confirm that everything is working correctly.

node v. 16.18.1
cypress v. 12.10.0

on a mac mini m1

Thanks for following up.
