### ISSUE TITLE
The `rightclick()` test on the example pages shows the incorrect selectors

### ISSUE THREAD

**Issue by DionisIno** [cypress-io/cypress-example-kitchensink#587]
### Current behavior
The [rightclick()](https://example.cypress.io/commands/actions) example shows the following selectiors:

```js
cy.get('.action-div').rightclick().should('not.be.visible')
cy.get('.action-input-hidden').should('be.visible')
```

### Desired behavior

The selectors should be:

```js
cy.get('.rightclick-action-div').rightclick().should('not.be.visible')
cy.get('.rightclick-action-input-hidden').should('be.visible')
```

### Cypress Version

12.5.0

### Node version

v19.4.0

### Operating System

Windows 11, version 22H2

**Comment by DionisIno** [comment]
That would be great!

**Comment by DionisIno** [comment]
Good afternoon. I don't know git very well. Submitted the changes, but the first 10 checks failed. Can you advise me how to proceed?

**Comment by mschile** [comment]
Thanks @DionisIno, it looks like there is an issue with the Record Key which is not something you can change. I'll try and take a look later today.
