### ISSUE TITLE
Running cypress-example-kitchensink first time:  Opening E2E Testing in Chrome spinning wo/end

### ISSUE THREAD

**Issue by robertramirez05231999** [cypress-io/cypress-example-kitchensink#597]
Hello...just pulled repo (cypress-io/cypress-example-kitchensink) from github and ran following:

1. cd cypress-example-kitchensink
2. npm install (had to run **npm audit fix --force** but still have 12 vulnerabilities (3 moderate, 5 high, 4 critical)
3. npm Start

```
xxxxxxxxxxx cypress-example-kitchensink % npm start

> cypress-example-kitchensink@0.0.0-development start
> node ./scripts/start.js

Running "serve --listen 8080"...

   ┌──────────────────────────────────────────┐
   │                                          │
   │   Serving!                               │
   │                                          │
   │   - Local:    http://localhost:8080      │
   │   - Network:  http://192.168.4.36:8080   │
   │                                          │
   │   Copied local address to clipboard!     │
   │                                          │
   └──────────────────────────────────────────┘

 HTTP  3/16/2023 2:04:48 AM ::1 GET /
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 13 ms
 HTTP  3/16/2023 2:04:48 AM ::1 GET /assets/css/vendor/bootstrap.min.css
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 1 ms
 HTTP  3/16/2023 2:04:48 AM ::1 GET /assets/css/vendor/fira.css
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 1 ms
 HTTP  3/16/2023 2:04:48 AM ::1 GET /assets/css/styles.css
 HTTP  3/16/2023 2:04:48 AM ::1 GET /assets/js/vendor/jquery-1.12.0.min.js
 HTTP  3/16/2023 2:04:48 AM ::1 GET /assets/js/vendor/bootstrap.min.js
 HTTP  3/16/2023 2:04:48 AM ::1 GET /assets/js/vendor/highlight.pack.js
 HTTP  3/16/2023 2:04:48 AM ::1 GET /assets/js/scripts.js
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 11 ms
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 2 ms
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 3 ms
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 3 ms
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 5 ms
 HTTP  3/16/2023 2:04:48 AM ::1 GET /assets/fonts/woff/FiraSans-Regular.woff
 HTTP  3/16/2023 2:04:48 AM ::1 GET /assets/fonts/woff/FiraSans-Medium.woff
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 2 ms
 HTTP  3/16/2023 2:04:48 AM ::1 Returned 304 in 2 ms
```

5. Cypress dashboard opens and I chose e2e testing, Select Chrome
6. Get "Still waiting...1->62
```
Still waiting to connect to Chrome, retrying in 1 second (attempt 59/62)
Still waiting to connect to Chrome, retrying in 1 second (attempt 60/62)
Still waiting to connect to Chrome, retrying in 1 second (attempt 61/62)
Still waiting to connect to Chrome, retrying in 1 second (attempt 62/62)
```
7. Browser windows does open w/"Chrome is being controlled by..." message

I haven't updated any files but things don't seem to be working....missing steps?

**Comment by robertramirez05231999** [comment]
More:
Running: `npx cypress run` runs all 124 tests. So that looks good running.
Running: `npm run local:open ` I get same results as above...browser opens, attempt to connect and no test run.

**Comment by MikeMcC399** [comment]
@robertramirez05231999 

1. If you use `npm audit fix --force` then you are installing **BREAKING CHANGES**. I am surprised that it even works, but I did try this on Ubuntu 22.04 and confirmed that the tests do indeed run. I would not recommend this however. `npm audit fix` would be OK, but `npm audit fix --force` puts you in an unsupported state.
2. Your screenshot shows 
`http://localhost:63409`
`This port was picked because 8080 is in use.`
That means you have started two servers in parallel. Close down all running servers e.g. by closing all open terminal windows, and then execute `npm run local:run`.

**Comment by MikeMcC399** [comment]
- I have submitted https://github.com/cypress-io/cypress-example-kitchensink/pull/598 to remove the critical vulnerabilities so you don't get tempted to run `npm audit fix --force` anymore 🙂

**Comment by JudeaDumont** [comment]
I can't get visit to work for anything in the cypress browser. I can hit it fine in a browser I open myself though. Tests all timeout waiting for the page to load.

**Comment by JudeaDumont** [comment]
Tried moving all kinds of dependencies around, nothing works. I can hit the served content in http://localhost:8080/todo in a browser I open myself, but cypress looks like this: 
![image](https://user-images.githubusercontent.com/31213205/226214167-7b6c6ddb-d104-4556-9acb-f830e4076899.png)

**Comment by robertramirez05231999** [comment]
I ended up removing and reinstalling…maybe issue with installing non via
installer rather than cmd?  Did get it to work after all

**Comment by MikeMcC399** [comment]
@robertramirez05231999 

If it is now working, then I suggest to close the issue.

**Comment by MikeMcC399** [comment]
The critical vulnerabilities have been removed through PR https://github.com/cypress-io/cypress-example-kitchensink/pull/598. Sync the fork and re-run `npm install` to take advantage of this.

**Comment by emilyrohrbough** [comment]
Closing as it sounds like this issue is resolved. @robertramirez05231999 please add additional information if you are still experiencing this issue.
