### ISSUE TITLE
Travis CI inactive on https://travis-ci.org

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-example-kitchensink#602]
## Problem description

The original issue that I noticed was that the Travis badge was broken. Apparently this was just a transient problem, since it is now showing a status.

[README.md](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) links to

[![Travis CI](https://travis-ci.org/cypress-io/cypress-example-kitchensink.svg?branch=master)](https://travis-ci.org/cypress-io/cypress-example-kitchensink)

Attempting to display https://travis-ci.org/cypress-io/cypress-example-kitchensink.svg?branch=master manually in a browser previously resulted in `ERR_TOO_MANY_REDIRECTS`, now it displays a banner indicating that the site has migrated.

## Repro steps

View https://travis-ci.org/cypress-io/cypress-example-kitchensink

## Expected

The Travis CI badge should show the results of running Travis CI on the current version of the repo.
The results should be success.

## Suggestion

The domain being addressed is `travis-ci.org` and https://docs.travis-ci.com/user/migrate/open-source-repository-migration states

"Starting June 2021 travis-ci.org is disabled and therefore no longer supported. Please use travis-ci.com."

So it seems that the Cypress.io team needs to sign in to `travis-ci.com` and migrate the repository `cypress-example-kitchensink`.

**Comment by lmiller1990** [comment]
My understanding is Travis got acquired and ran into the ground, it's basically obsolete at this point.

**Comment by MikeMcC399** [comment]
@lmiller1990 

> My understanding is Travis got acquired and ran into the ground, it's basically obsolete at this point.

I don't get the impression that they are no longer in business

- https://github.com/travis-ci 
- https://changelog.travis-ci.com/
- https://travis-ci.community/

all have recent updates. However I did read that they no longer offer free unlimited use for Open Source Software. Following my suggestion to migrate to `travis-ci.com` might therefore lead to additional problems of running out of quota. Possibly Travis CI might like to make an exception for Cypress, since it is a form of advertising for them, however that opens up extra workload.

Given that the status badge
[![Travis CI](https://travis-ci.org/cypress-io/cypress-example-kitchensink.svg?branch=master)](https://travis-ci.org/cypress-io/cypress-example-kitchensink)
is now showing success, I suggest to take no further steps at this time and to close this issue.

**Comment by lmiller1990** [comment]
Right, gotcha. Let's wait a bit. I'm still thinking this is low priority - after a lot of internal turmoil and the Travis acquisition, and what looks like a pretty unreliable service (why it is 503ing?!) it's very rare to see or recommend using it nowadays.

**Comment by MikeMcC399** [comment]
```text
$ curl -I https://travis-ci.org/cypress-io/cypress-example-kitchensink
HTTP/2 503
date: Wed, 29 Mar 2023 09:06:50 GMT
content-type: text/html
strict-transport-security: max-age=15724800; includeSubDomains
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=YgVablUvKDsBHYsS3nxQ6KqIPp%2FzmrXjQ3WbhCI00CqNEQc%2BTp%2FPaFt%2F0%2F3100dHWNFGTrfgct%2B1gg368tqQQP2ERuv0SBHXtofvgOMeuzIM8xy8jnJ3CN4skTA8zSnb3eYVsn7qOavTaXNN"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 7af6f58769936d83-MUC
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by MikeMcC399** [comment]
Searching in the Cypress.io organization shows that the use of `.travis.yml` is widespread.

https://github.com/search?q=org%3Acypress-io+.travis.yml++NOT+is%3Aarchived&type=code

Although there could be a decision made only for this repo, it probably needs some management attention to decide what happens with all the other non-archived repos which are linked to the use of Travis CI.

**Comment by lmiller1990** [comment]
I can look into what we want to do, but I don't think fixing Travis is something we are likely to prioritize right now, most of our resources are on the main repo and the Cloud offering.

I'd rather just remove it, since I don't expect to spend time fixing it in the near future.

**Comment by MikeMcC399** [comment]
@lmiller1990 

Removing Travis CI is probably the best solution, however it would also need to be removed first from https://docs.cypress.io/guides/continuous-integration/ci-provider-examples which refers to this repo. I can start this removal process next week, similar to what I did for Shippable.

**Comment by lmiller1990** [comment]
Let me check with @elylucas who generally manages the docs.

**Comment by lmiller1990** [comment]
@MikeMcC399 Yep, let's do it!

**Comment by MikeMcC399** [comment]
@lmiller1990 

- I have now submitted PR #624 to resolve this issue.

After having worked with this repo a bit more deeply I now understand that the table [CI Status table](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md#ci-status) is a mixture of live workflows and examples which only document what a workflow could look like.

That is probably something which could be better explained in the [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) with some edits done at some later time, however for the purpose of resolving this issue, it is sufficient to simply remove the failing Travis CI status badge. The workflows can stay there (unless we have reason to believe that they will not work on Travis CI's subscription service).
