### ISSUE TITLE
Circle CI fails on linux and release

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-example-kitchensink#606]
The status of Circle CI on https://circleci.com/gh/cypress-io/cypress-example-kitchensink/tree/master is showing as failed.

![Circle CI failed](https://user-images.githubusercontent.com/66998419/228852591-6538a0f2-9fa9-478d-b5e3-845870e0c92a.jpg)

The linux build is shown as failing since 29 days ago.

![Circle CI detail fail](https://user-images.githubusercontent.com/66998419/228852678-2cefc118-a93f-4be6-b89c-ef69ee24cf00.jpg)

![Circle CI detail fail release](https://user-images.githubusercontent.com/66998419/228852737-2330817e-ec70-4657-9088-effd3eb8241c.jpg)

This seems to be blocking releases from occurring.

**Comment by MikeMcC399** [comment]
- Problems started occurring after merging #591 from @jordanpowell88 

![image](https://user-images.githubusercontent.com/66998419/228938662-97c366c5-7fd4-4302-acae-bc63d1833fc1.png)

**Comment by lmiller1990** [comment]
Seems the v3 orb has a couple of issues: https://github.com/cypress-io/circleci-orb/issues/418

**Comment by MikeMcC399** [comment]
@lmiller1990 

- @emilyrohrbough submitted #607 to resolve this issue
