### ISSUE TITLE
Sync of GitLab mirror copy

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-example-kitchensink#615]
## Background

~~Currently the CI build status for GitLab listed in [github.com/cypress-io/cypress-example-kitchensink: README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) shows~~

![image](https://user-images.githubusercontent.com/66998419/230456700-b86b918e-58fc-47d9-9244-929dff7ff3c5.png)

Edit: the status badge is now removed from the README.

The success of the GitLab CI workflow depends on:

1. correctness of the workflow [.gitlab-ci.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.gitlab-ci.yml)
2. synchronization with this, the parent, GitHub repository

- An update to the workflow is pending in PR https://github.com/cypress-io/cypress-example-kitchensink/pull/614 Edit: this is now resolved.

The mirror copy of https://github.com/cypress-io/cypress-example-kitchensink on https://gitlab.com/cypress-io/cypress-example-kitchensink/ is not in sync.

The last commit on the [GitLab mirror copy](https://gitlab.com/cypress-io/cypress-example-kitchensink/) is [d538683f](https://github.com/cypress-io/cypress-example-kitchensink/commit/d538683f) from Dec 7, 2022, belonging to PR #581 which is almost 4 months ago.

## Suggestions

1. Manually sync the parent [GitHub repository: cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) to the mirror copy [GitLab clone: cypress-io/cypress-example-kitchensink/](https://gitlab.com/cypress-io/cypress-example-kitchensink/).

2. Set up an automatic sync of the parent [GitHub repository: cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) to the mirror copy [GitLab clone: cypress-io/cypress-example-kitchensink/](https://gitlab.com/cypress-io/cypress-example-kitchensink/).

**Comment by emilyrohrbough** [comment]
oh yikes, this is weird we are keeping a clone of this in GitLab. Spoke with the team, we are not interested in maintain two copies of this repo and would like to use Github as the source of true. I'll add to our backlog to archive the GitLab repo.

Can we remove references to this repo and update the GitLab CI workflow to have a comment saying this should work but hasn't been recently tested and ensure there is a link to the offical docs?

**Comment by MikeMcC399** [comment]
@emilyrohrbough 

- Many thanks for taking the decision to archive the GitLab repo. This step would resolve the issue which was highlighting the lack of synchronization. Synchronization is no longer necessary or possible in this case.

- I have submitted PR #625 to remove the GitLab CI status badge from the README. It then becomes like most of the other examples, which are "documentation-only". I would like to revisit the whole list of examples at a later time and reorganize how they are presented. They are a mixture of live examples, documentation-only examples and legacy examples using old Cypress versions.

- So, taken together your backlog item to archive the GitLab repo and the PR#625 will clean things up. I will leave this issue open until both points have been taken care of.

**Comment by MikeMcC399** [comment]
The only remaining item for this issue is to archive the GitLab repo

    https://gitlab.com/cypress-io/cypress-example-kitchensink/

I guess that the https://github.com/cypress-io/cypress-example-kitchensink/labels/help%20wanted label can be removed. Archiving would need to be done by the Cypress.io team.

See https://docs.gitlab.com/ee/user/project/settings/#archive-a-project.

**Comment by MikeMcC399** [comment]
https://gitlab.com/cypress-io/cypress-example-kitchensink/ is now archived.
