### ISSUE TITLE
Login Windows

### ISSUE THREAD

**Issue by DavidTNguyen** [cypress-io/cypress-example-kitchensink#64]
When the login process started the auth form in a separate tab, like oAuth2, there is no way to get hold of either collection of windows or tabs in the current library. 

cy.window() doesn't get me to the form where username/password elements are located.

**Comment by jennifer-shehane** [comment]
Hi - I believe you meant to open this as a general issue in Cypress. General issues can be opened here: https://github.com/cypress-io/cypress/issues/new

This repository is only meant for issues with our kitchensink example app.
