### ISSUE TITLE
Several advanced examples fail cypress/unsafe-to-chain-command lint rule

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-example-kitchensink#661]
If the eslint rule `cypress/unsafe-to-chain-command` from [eslint-plugin-cypress: Rules](https://github.com/cypress-io/eslint-plugin-cypress#rules) is enabled, then the following 6 examples in [cypress/e2e/2-advanced-examples](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e/2-advanced-examples) fail linting with the message:

"error  It is unsafe to chain further commands that rely on the subject after this command. It is best to split the chain, chaining again from `cy.` in a next command line  cypress/unsafe-to-chain-command"

"✖ 57 problems (51 errors, 0 warnings)"

- [actions.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e/2-advanced-examples/actions.cy.js)
- [cookies.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/e2e/2-advanced-examples/cookies.cy.js)
- [misc.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e/2-advanced-examples/misc.cy.js)
- [spies_stubs_clocks.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js)
- [storage.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e/2-advanced-examples/storage.cy.js)
- [utilities.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e/2-advanced-examples/utilities.cy.js)

Here is a portion of [actions.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e/2-advanced-examples/actions.cy.js) which fails linting:

```js
    cy.get('.action-email')
      .type('fake@email.com').should('have.value', 'fake@email.com')

      // .type() with special character sequences
      .type('{leftarrow}{rightarrow}{uparrow}{downarrow}')
      .type('{del}{selectall}{backspace}')

      // .type() with key modifiers
      .type('{alt}{option}') //these are equivalent
      .type('{ctrl}{control}') //these are equivalent
      .type('{meta}{command}{cmd}') //these are equivalent
      .type('{shift}')

      // Delay each keypress by 0.1 sec
      .type('slow.typing@email.com', { delay: 100 })
      .should('have.value', 'slow.typing@email.com') 
```

## Expectation

Since the rule `cypress/unsafe-to-chain-command` is part of `plugin:cypress/recommended` rules according to [eslint-plugin-cypress: Rules](https://github.com/cypress-io/eslint-plugin-cypress#rules) I would expect standard examples to pass this lint test.

## Steps to reproduce

Add `"cypress/unsafe-to-chain-command": "error"` to `rules` of [.eslintrc](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.eslintrc), similar to the following

```json
  "rules": {
    "cypress/unsafe-to-chain-command": "error"
  }
```

Execute:

```bash
npm run lint
```

Reproducible example on https://github.com/MikeMcC399/cypress-example-kitchensink/tree/test/unsafe-to-chain

## Environment

- [eslint@8.53.0](https://github.com/eslint/eslint)
- [eslint-plugin-cypress@2.15.1](https://github.com/cypress-io/eslint-plugin-cypress) (current `latest`)

## Next steps

- [ ] Correct the examples

**Comment by mschile** [comment]
Hi @MikeMcC399 👋, thanks for logging this issue. I took a cursory look at the reported errors and the rule appears to be correct so we should do `#2` and update the examples.

**Comment by MikeMcC399** [comment]
Hi  @mschile 

Thank you very much for qualifying this issue!

I can't provide a solution for this issue, so I would be happy for the core team to make the changes in the examples.

**Comment by MikeMcC399** [comment]
- I have proposed a fix for a related issue in https://github.com/cypress-io/cypress-example-kitchensink/pull/662. In this case I propose to ignore the rule.

**Comment by MikeMcC399** [comment]
@mschile 

`unsafe-to-chain` is currently disabled in this repo pending update of the examples to conform to linting rules.

The latest new release from Aug 8, 2023 [eslint-plugin-cypress@2.14.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.14.0) causes additional 8 problems to be flagged if the rule is enabled:

✖ 59 problems (59 errors, 0 warnings)

instead of the previous 

✖ 51 problems (51 errors, 0 warnings)

It would be good for the examples to be updated so that they can be used as a reference for what is correct. Perhaps this fix could be scheduled some time soon?

**Comment by MikeMcC399** [comment]
Updating to [eslint-plugin-cypress@2.15.1](https://github.com/cypress-io/eslint-plugin-cypress) (current `latest`) causes now 59 "unsafe to chain" errors when checking with

```
  "rules": {
    "cypress/unsafe-to-chain-command": "error"
  }
```

The rule is currently disabled and waiting for the examples to be corrected so they conform to the chaining rules as described in the https://docs.cypress.io/api/table-of-contents documentation.

https://github.com/cypress-io/cypress-example-kitchensink/blob/a3327d9af69f78cc3f7d52e7477c5f067f07c8f3/.eslintrc#L17-L18

**Comment by MikeMcC399** [comment]
Unfortunately I'm unable to provide a PR to resolve this issue, which remains unaddressed.

## Steps to reproduce

Comment out

https://github.com/cypress-io/cypress-example-kitchensink/blob/b49f532c383335ee8d5d8c1fa403b50e4cef496a/.eslintrc#L18

and then execute

```shell
npm run lint
```

shows

```text
✖ 57 problems (57 errors, 0 warnings)
```

**Comment by enchorb** [comment]
+1

**Comment by jennifer-shehane** [comment]
@MikeMcC399 I'd be fine with an update to the example recipes to reflect our new conventions. We just never revisited this.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> @MikeMcC399 I'd be fine with an update to the example recipes to reflect our new conventions. We just never revisited this.

This issue is still open because as I said previously I don't have the skills for this and nobody else has picked it up.
