### ISSUE TITLE
Azure Pipelines example uses non-recommended code

### ISSUE THREAD

**Issue by Zhaph** [cypress-io/cypress-example-kitchensink#664]
In the example for running Cypress on [Azure DevOps pipelines](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/azure-ci.yml) the following example is given:

```
# The next command starts the server and runs Cypress end-to-end tests against it.
      # The test artifacts (video, screenshots, test output) will be uploaded to Cypress dashboard.
      # To record on Cypress dashboard we need to set CYPRESS_RECORD_KEY environment variable.
      # For setting ci-build-id, BUILD_BUILDNUMBER is a good candidate
      - script: |
          npx print-env AGENT
          npx print-env BUILD
          npx print-env SYSTEM
          npm run start &
          npx cypress run --record --parallel --ci-build-id $BUILD_BUILDNUMBER --group "Azure CI"
        displayName: 'Run Cypress tests'
        env:
          # avoid warnings about terminal
          TERM: xterm
          # map the secret Cypress record key as environment variable for this step
          CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)
```

This results in a long running server that never shuts down, blocking the rest of the pipeline from running.

In your "Continuous Integration" documentation under [Booting your server](https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server) you explicitly call out that this is not the way to do it:

> Many people approach this situation by running a command like the following:
> `npm start & cypress run // Do not do this`
> The problem is - what happens if your server takes time to boot? There is no guarantee that when the next command runs (cypress run) that your web server is up and available. So your Cypress test may start and try to visit your local server before it is ready to be visited.

The example code should either be annotated to warn that running it like this is not recommended, or implement best practices so others can fall into the pit of success.

As it stands, running the above code on Azure Hosted build agents results in a task that never completes until the job is failed for overrunning it's allocated time.

**Comment by marktnoonan** [comment]
Thanks @Zhaph, I've made a PR to add this note, I'll let the team review that PR and decide if we need to update the example itself.

Appreciate this report! Pit of success is a good thing.
