### ISSUE TITLE
CircleCI runs Windows tests under unsupported Node.js 14 - renovate fails

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-example-kitchensink#721]
## Issue

Windows tests in CircleCI specified through [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.yml) use the image `windows-server-2019-vs2019:stable` with the now unsupported Node.js `14.17.5` version.

1. renovate's PR https://github.com/cypress-io/cypress-example-kitchensink/pull/720 fails in [CircleCI Windows](https://app.circleci.com/pipelines/github/cypress-io/cypress-example-kitchensink/1586/workflows/6b791d8c-1ae1-4af2-a508-cf2e5ec4f5d5) with `npm ERR! Cannot read property 'npm-run-all' of undefined`. This PR is attempting to bump the `lockfileVersion` in [package-lock.json](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/package-lock.json) from `2` to `3`. npm [`lockfileVersion`](https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#lockfileversion) `3` is used by npm v9, however it is only backwards compatible to npm v7. Node.js `14.17.5` is configured with the earlier version npm `6.14.14` thus causing a compatibility issue.
2. Node.js `14` entered [end-of-life](https://github.com/nodejs/release#release-schedule) on April 30, 2023.
3. [.node-version](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.node-version) specifies Node.js `18` as the required version for this repo.

## Suggestion

Update [.circleci/config.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.yml) to run under Node.js `18` (currently the LTS version) for the Windows tests.

**Comment by MikeMcC399** [comment]
I don't have the experience with CircleCI to confidently attempt this change, so I need to leave it to somebody else with the right skills.

I noticed also that an older version of Windows Server is being used. Would it be a good time to upgrade this as well?

https://github.com/cypress-io/cypress-example-kitchensink/blob/b8e17bda4094988578657b92a56cc81df90d1856/.circleci/config.yml#L22

**Comment by nagash77** [comment]
Hi @MikeMcC399 , yeah it looks like we need to upgrade the image as you suggested.  Thanks for opening this issue so we can track this work and hopefully find some time to do this.

**Comment by MikeMcC399** [comment]
@AtofStryker 

Could you perhaps look at this issue also as part of your updating work for Node.js `18`? It needs some tweaking on CircleCI for Windows.

**Comment by AtofStryker** [comment]
@MikeMcC399 https://github.com/cypress-io/cypress-example-kitchensink/pull/739 should get us to Node 20
