### ISSUE TITLE
Missing API commands

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-example-kitchensink#796]
## Issue

The [README](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/README.md) description of this repo says that "every API command in Cypress" is tested. This is not completely the case.

> This is an example app used to showcase [Cypress.io](https://www.cypress.io/) testing. The application uses every API command in Cypress for demonstration purposes. Additionally this example app is configured to run tests in various CI platforms. The [tests](https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e) are also heavily commented. For a full reference of our documentation, go to [docs.cypress.io](https://docs.cypress.io/).

### Missing API commands

The Cypress tests in [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) do not cover the following commands. They are also not described in the app on https://example.cypress.io/:

- [cy.origin()](https://docs.cypress.io/api/commands/origin)
- [cy.selectFile()](https://docs.cypress.io/api/commands/selectfile)
- [cy.shadow()](https://docs.cypress.io/api/commands/shadow)
- [cy.pause()](https://docs.cypress.io/api/commands/pause) (only makes sense to be used manually)
- [cy.session()](https://docs.cypress.io/api/commands/session)
- [cy.task()](https://docs.cypress.io/api/commands/task)

## Suggestion

1. Either add the missing commands (see above) to the Cypress tests in [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) and to the descriptions in the app on https://example.cypress.io/ OR
2. Modify the text to avoid implying that every available Cypress API command is tested.

**Comment by jennifer-shehane** [comment]
Yah, we did take some preference towards putting some of these more complicated uses in the realworld app application (like session and origin). I wouldn't be opposed to adding more examples that cover these and reviewing the PRs, but this won't be a priority for us to add. 

You could update the text to say there are expanded real case examples in the realworld-app for some of the other commands.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Thanks for the background information! I'll pick up your suggestion to make a text proposal.
