### ISSUE TITLE
Update HTML examples to conform to scaffolded tests

### ISSUE THREAD

**Issue by cacieprins** [cypress-io/cypress-example-kitchensink#804]
The HTML that gets deployed to `example.cypress.io` for, e.g., commands, should align with the tests that get scaffolded from `cypress/*`

**Comment by MikeMcC399** [comment]
@cacieprins 

> The HTML that gets deployed to `example.cypress.io` for, e.g., commands, should align with the tests that get scaffolded from `cypress/*`

Is this an issue for this repo or for the build and deploy process defined in https://github.com/cypress-io/cypress/tree/develop/packages/example ?

**Comment by jennifer-shehane** [comment]
@MikeMcC399 It's an issue with this repo. This PR updated the test files: https://github.com/cypress-io/cypress-example-kitchensink/pull/802/files but there is HTML that reflects the code in the test files that should be updated. https://example.cypress.io/commands/actions

![Screenshot 2024-03-14 at 12 21 51 PM](https://github.com/cypress-io/cypress-example-kitchensink/assets/1271364/c2c55cc1-9ed1-4ac1-8558-7416b43ecea0)

**Comment by MikeMcC399** [comment]
Perhaps @rubysolo would like to follow up with a related PR to change the HTML to match the tests?

For instance, the following would need to be aligned:

https://github.com/cypress-io/cypress-example-kitchensink/blob/9755df4a0addcfe8bbee59fa8faa4f21522e0b84/app/commands/actions.html#L80-L88

https://github.com/cypress-io/cypress-example-kitchensink/blob/9755df4a0addcfe8bbee59fa8faa4f21522e0b84/cypress/e2e/2-advanced-examples/actions.cy.js#L15-L23

**Comment by rubysolo** [comment]
Oh, I assumed those were generated.  Would there be any interest in templatizing the example HTML files so that they could be autogenerated from the examples with a script?

**Comment by jennifer-shehane** [comment]
@rubysolo We don't update these examples very often honestly, so I don't think there'd be a lot of utility with that.

**Comment by rubysolo** [comment]
One question I had -- the tests no longer call `end`, since `click` isn't chainable.  Is there a better example of using `end` that we could use in the tests / docs?

**Comment by MikeMcC399** [comment]
@rubysolo 

> One question I had -- the tests no longer call `end`, since `click` isn't chainable. Is there a better example of using `end` that we could use in the tests / docs?

Apparently nobody noticed that the `.end` test had been deactivated. Although that achieved the goal of passing linting, it was at the expense of no longer demonstrating `cy.end`.

I've raised the following interrelated issues accordingly:

- https://github.com/cypress-io/cypress-documentation/issues/5752
- https://github.com/cypress-io/cypress-documentation/issues/5753
- https://github.com/cypress-io/cypress-example-kitchensink/issues/808

**Comment by jennifer-shehane** [comment]
I'd be in favor of removing the .end example I think.
