### ISSUE TITLE
Documentation Bug - It says "4x-electron" instead of "2x-electron" in the comments for the 2x-electron build job

### ISSUE THREAD

**Issue by henrik-andersson** [cypress-io/cypress-example-kitchensink#905]
https://github.com/cypress-io/cypress-example-kitchensink/blob/aabb10cc1bb9dee88e1bf28e0af5e9661427ee7a/circle.yml#L64

I assume this is just a copy-paste error.

Steps:

1. Go to the 2x build: https://github.com/cypress-io/cypress-example-kitchensink/blob/aabb10cc1bb9dee88e1bf28e0af5e9661427ee7a/circle.yml#L64
Expected: # and groups them in Cypress Dashboard under name "2x-electron"
Actual: # and groups them in Cypress Dashboard under name "4x-electron"

**Comment by MikeMcC399** [comment]
@henrik-andersson 

You are referring to commit https://github.com/cypress-io/cypress-example-kitchensink/commit/aabb10cc1bb9dee88e1bf28e0af5e9661427ee7a from November 2018.

Please check the current version https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.circleci/config.yml and let us know if you still see any discrepancies.

**Comment by henrik-andersson** [comment]
@MikeMcC399 
Seems fine in the current version. I guess we can close this issue.

**Comment by henrik-andersson** [comment]
Perhaps I should create a new issue on the link that took me to the old file.
![image](https://github.com/user-attachments/assets/8388f571-a545-4db3-8646-39107fc2bdd4)

**Comment by MikeMcC399** [comment]
@henrik-andersson 

Thanks very much for explaining how you got to the old contents! You are welcome to open an issue in https://github.com/cypress-io/cypress-documentation/issues. If you don't want to do this, then please let me know and I will do it.

**Comment by henrik-andersson** [comment]
I created a [new issue](https://github.com/cypress-io/cypress-documentation/issues/5988)
